# Simple script to setup Stunnel for SSL proxy for Postgres
# - Assumes Ubuntu or other apt based distribution
# - Works only for initial install

POSTGRES_HOST=
STUNNEL_SETUP_STRING="# Generated by stunnel-setup.sh"
STUNNEL_CONFIG_FILE="/etc/stunnel/stunnel.conf"

# Colour codes
red=$'\e[1;31m'
grn=$'\e[1;32m'
end=$'\e[0m'

# Parse Params
while :; do
  case $1 in
      -\?|--help)
          printf "Install and configure Stunnel for Postgres.\n"
          printf "Usage: ${0##*/} -h <host> \n"
          printf "   -h --host TEXT  Host address of the Postgres database.\n"
          printf "   -? --help       this message\n"
          exit
          ;;
      -h|--host)
          if [ "$2" ]; then
            POSTGRES_HOST=$2
            shift
          else
             printf "${red}ERROR: --host requires Postgres host to be specified${end}\n"
             exit 1
          fi
          ;;
      -?*)
          printf "${red}ERROR: Unknown option (ignored): %s${end}\n" "$1" >&2
          exit 1
          ;;
      *)
          break
  esac
  shift
done

if [ -z ${POSTGRES_HOST+x} ]; then
  printf "${red}ERROR: Postgres host needs to be specified with --host${end}\n"
  exit 1
fi

if [ -f $STUNNEL_CONFIG_FILE ]; then
   printf "${red}** Stunnel Setup - Stunnel already installed. Exiting.  ************************${end}\n"
   exit 1
fi

printf "${grn}** Stunnel Setup - Updating apt packages ***************************************${end}\n"
sudo apt-get update || exit

printf "${grn}** Stunnel Setup - Downloading Stunnel *****************************************${end}\n"
sudo apt-get -q install stunnel4 || exit

printf "${grn}** Stunnel Setup - Generating config file **************************************${end}\n"
# echo redirect doesn't run as sudo, so use tee to generate file
echo "$STUNNEL_SETUP_STRING
client = yes
pid = /tmp/stunnel-postgres.pid

[postgres-server]
protocol = pgsql
accept = 5432
connect = $POSTGRES_HOST:5432
options = NO_TICKET
retry = yes" | sudo tee -a $STUNNEL_CONFIG_FILE || exit

printf "${grn}** Stunnel Setup - Enabling Stunnel SSL ****************************************${end}\n"
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/stunnel4 || exit

printf "${grn}** Stunnel Setup - Restarting Stunnel service **********************************${end}\n"
sudo service stunnel4 restart|| exit

printf "${grn}** Stunnel Setup - Done ********************************************************${end}\n"

